/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connectpeople;

import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class cadastroTelaProfissional extends javax.swing.JFrame {

    /**
     * Creates new form cadastroTelaProfissional
     */
    public cadastroTelaProfissional() {
        super("Connect People");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeProTextField = new javax.swing.JTextField();
        emailProTextField = new javax.swing.JTextField();
        cpfProTextField = new javax.swing.JTextField();
        crpProTextField = new javax.swing.JTextField();
        cadastroProButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Profissional");

        nomeProTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Completo"));
        nomeProTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProTextFieldActionPerformed(evt);
            }
        });

        emailProTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        emailProTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailProTextFieldActionPerformed(evt);
            }
        });

        cpfProTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        cpfProTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfProTextFieldActionPerformed(evt);
            }
        });

        crpProTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("CRP"));
        crpProTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crpProTextFieldActionPerformed(evt);
            }
        });

        cadastroProButton.setBackground(new java.awt.Color(51, 204, 0));
        cadastroProButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastroProButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastroProButton.setText("Cadastre-se");
        cadastroProButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        senhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilherme\\Documents\\icons\\sair-button-icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomeProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crpProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cpfProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(voltarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroProButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crpProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastroProButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeProTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProTextFieldActionPerformed

    private void emailProTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailProTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailProTextFieldActionPerformed

    private void cpfProTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfProTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfProTextFieldActionPerformed

    private void crpProTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crpProTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crpProTextFieldActionPerformed

    private void cadastroProButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProButtonActionPerformed
        // TODO add your handling code here:
        String nome = nomeProTextField.getText();
        String email = emailProTextField.getText();
        String senha = new String(senhaPasswordField.getPassword());
        String cpf = cpfProTextField.getText();
        String crp = crpProTextField.getText();        
        //Validação do Nome
       if (nome.length() == 0){
            JOptionPane.showMessageDialog(null, "Nome Inválido");
        } 
        else {
            for (int i = 0; i < nome.length(); i++){
                char letra = nome.charAt(i);
                boolean possuiNumero = (Character.isDigit(letra));
                boolean naoLetra = (!Character.isLetter(letra) && (!nome.contains(" ")));
                
            if (possuiNumero){
                JOptionPane.showMessageDialog(null, "Nome Inválido");
                break;
            } else if (naoLetra){
                JOptionPane.showMessageDialog(null, "Nome Inválido");
                break;
                }
            }
        }        
        // Validação do Email
        if (email.length() == 0){
            JOptionPane.showMessageDialog(null, "Email Inválido");
        } else if (!email.contains("@" ) || !email.contains(".")) {
            JOptionPane.showMessageDialog(null, "Informe um email válido");
        }        
        // Validação da senha
        if (senha.length() == 0){
            JOptionPane.showMessageDialog(null, "Senha Inválida");
        } else if (senha.length() < 8){
            JOptionPane.showMessageDialog(null, "Senha deve ter no mínimo 8 caracteres");
        }
        
        // Validação do CPF
        if (cpf.length() == 0){
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        } 
        else if (cpf.length() != 11){
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        } else {
            for (int i = 0; i < cpf.length(); i++){
                char digito = cpf.charAt(i);
                boolean possuiLetra = (Character.isLetter(digito));
                boolean nao_eNumero = (!Character.isDigit(digito));
                
                if (possuiLetra || nao_eNumero){
                    JOptionPane.showMessageDialog(null, "CPF inválido.");
                    break;
                }
            }
        }        
        //Validação CRP
        if (crp.length() == 0) {
            JOptionPane.showMessageDialog(null, "CRP inválido");
        }
        else if (crp.length() != 8){
            JOptionPane.showMessageDialog(null, "CRP inválido");
        }
        else {
            for (int i = 0; i < crp.length(); i++) {
                char digito = crp.charAt(i);
                boolean possuiLetra = (Character.isLetter(digito));
                boolean nao_eNumero = (!Character.isDigit(digito));
            
                if (possuiLetra || nao_eNumero){
                    JOptionPane.showMessageDialog(null, "CRP inválido");
                    break;
                }
            }
        }
        //Integração com banco de dados
        try {
            Profissional profissional = new Profissional(nome, email, senha, cpf, crp);
            DAO dao = new DAO();
            //Caso o usuario ja exista, é mostrado o erro
            if (dao.cadastroExistenteProfissional(profissional)) {
                JOptionPane.showMessageDialog(null, "Usuario ja existe");
            }
            else {
                //adiciona no banco de dados
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas tecnicos");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cadastroProButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        opcoesTela opcoes = new opcoesTela();
        opcoes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroTelaProfissional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroProButton;
    private javax.swing.JTextField cpfProTextField;
    private javax.swing.JTextField crpProTextField;
    private javax.swing.JTextField emailProTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeProTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
