/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connectpeople;

import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class cadastroTelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form cadastroTela2
     */
    public cadastroTelaUsuario() {
        super("Connect People");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeUsuarioTextField = new javax.swing.JTextField();
        emailUsuarioTextField = new javax.swing.JTextField();
        cpfUsuarioTextField = new javax.swing.JTextField();
        cadastroUserButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Usuário");

        nomeUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Completo"));
        nomeUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioTextFieldActionPerformed(evt);
            }
        });

        emailUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        emailUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuarioTextFieldActionPerformed(evt);
            }
        });

        cpfUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        cpfUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfUsuarioTextFieldActionPerformed(evt);
            }
        });

        cadastroUserButton.setBackground(new java.awt.Color(0, 255, 51));
        cadastroUserButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cadastroUserButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastroUserButton.setText("Cadastre-se");
        cadastroUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUserButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        senhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeUsuarioTextField)
                                    .addComponent(emailUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cpfUsuarioTextField)
                                    .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cadastroUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(178, 178, 178))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastroUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomeUsuarioTextFieldActionPerformed

    private void emailUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailUsuarioTextFieldActionPerformed

    private void cpfUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cpfUsuarioTextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        opcoesTela opcoes = new opcoesTela();
        opcoes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void cadastroUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUserButtonActionPerformed
        // TODO add your handling code here:
        String nome = nomeUsuarioTextField.getText();
        String email = emailUsuarioTextField.getText();
        String senha = new String (senhaPasswordField.getPassword());
        String cpf = cpfUsuarioTextField.getText();
        
        // Validação do Nome
        if (nome.length() == 0){
            JOptionPane.showMessageDialog(null, "Nome Inválido");
        } 
        else {
            for (int i = 0; i < nome.length(); i++){
                char letra = nome.charAt(i);
                boolean possuiNumero = (Character.isDigit(letra));
                boolean naoLetra = (!Character.isLetter(letra) && (!nome.contains(" ")));
                
            if (possuiNumero){
                JOptionPane.showMessageDialog(null, "Nome Inválido");
                break;
            } else if (naoLetra){
                JOptionPane.showMessageDialog(null, "Nome Inválido");
                break;
                }
            }
        }
        
        // Validação do Email
        if (email.length() == 0){
            JOptionPane.showMessageDialog(null, "Email Inválido");
        } else if (!email.contains("@" ) || !email.contains(".")) {
            JOptionPane.showMessageDialog(null, "Informe um email válido");
        }
        
        // Validação da senha
        if (senha.length() == 0){
            JOptionPane.showMessageDialog(null, "Senha Inválida");
        } else if (senha.length() < 8){
            JOptionPane.showMessageDialog(null, "Senha deve ter no mínimo 8 caracteres");
        }
        
        // Validação do CPF
        if (cpf.length() == 0){
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        } else if (cpf.length() != 11){
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        } else {
            for (int i = 0; i < cpf.length(); i++){
                char digito = cpf.charAt(i);
                boolean possuiLetra = (Character.isLetter(digito));
                boolean nao_eNumero = (!Character.isDigit(digito));
                
                if (possuiLetra || nao_eNumero){
                    JOptionPane.showMessageDialog(null, "CPF inválido.");
                    break;
                }
            }
        }
        // Integração com o banco de dados
        try {
            Usuario usuario = new Usuario(nome, email, senha, cpf);
            DAO dao = new DAO();
            //Caso o usuario ja exista, é mostrado o erro
            if (dao.cadastroExistente(usuario)) {
                JOptionPane.showMessageDialog(null, "Usuario ja existe");
            }
            else {
                //adiciona no banco de dados
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas tecnicos");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cadastroUserButtonActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroTelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroUserButton;
    private javax.swing.JTextField cpfUsuarioTextField;
    private javax.swing.JTextField emailUsuarioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeUsuarioTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
